// <auto-generated />
using System;
using EXE201_2RE_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201_2RE_API.Migrations
{
    [DbContext(typeof(EXE201Context))]
    [Migration("20241006152639_updateEntitiesV3")]
    partial class updateEntitiesV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Property<Guid?>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartId");

                    b.HasIndex("userId");

                    b.ToTable("tblCarts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.Property<Guid?>("cartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartDetailId");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("tblCartDetails");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Property<Guid?>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("tblCategories");

                    b.HasData(
                        new
                        {
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            name = "Áo Thun"
                        },
                        new
                        {
                            categoryId = new Guid("a7b8c9d8-3e2a-4b9b-b9f7-5e6a7c8e9f0b"),
                            name = "Quần Jeans"
                        },
                        new
                        {
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            name = "Áo Khoác"
                        },
                        new
                        {
                            categoryId = new Guid("e2b3d5a6-3e4f-5a6b-c8d9-2f2b3e5a7b8c"),
                            name = "Váy"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.Property<Guid?>("favoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("productId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("favoriteId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblFavorites");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Property<Guid?>("genderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderCategoryId");

                    b.ToTable("tblGenderCategories");

                    b.HasData(
                        new
                        {
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Nam"
                        },
                        new
                        {
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Nữ"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.Property<Guid?>("orderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("changedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderHistoryId");

                    b.HasIndex("cartId");

                    b.ToTable("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("categoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("genderCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("shopOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("genderCategoryId");

                    b.HasIndex("shopOwnerId");

                    b.HasIndex("sizeId");

                    b.ToTable("tblProducts");

                    b.HasData(
                        new
                        {
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6322),
                            description = "Áo thun cổ điển dành cho nam, có nhiều kích cỡ",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Cổ Điển Nam",
                            price = 200000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6323)
                        },
                        new
                        {
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6330),
                            description = "Quần jeans slim fit với kiểu dáng hiện đại",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Slim Fit Nam",
                            price = 300000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6331)
                        },
                        new
                        {
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "96%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6337),
                            description = "Áo khoác thường cho ngày thường",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Thường Nam",
                            price = 400000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6337)
                        },
                        new
                        {
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6343),
                            description = "Áo thun ôm thoải mái cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Ôm Nữ",
                            price = 250000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6343)
                        },
                        new
                        {
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "89%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6378),
                            description = "Quần jeans ôm thời trang cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Quần Jeans Ôm Nữ",
                            price = 350000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6379)
                        },
                        new
                        {
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6385),
                            description = "Áo khoác thời trang và ấm áp cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Khoác Thường Nữ",
                            price = 500000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6385)
                        },
                        new
                        {
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6391),
                            description = "Áo thun họa tiết thời trang với thiết kế đẹp",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Họa Tiết Nam",
                            price = 290000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6391)
                        },
                        new
                        {
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "85%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6397),
                            description = "Quần jeans regular fit cổ điển",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Regular Fit Nam",
                            price = 440000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6398)
                        },
                        new
                        {
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b"),
                            brand = "Nike",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "70%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6404),
                            description = "Áo khoác da cao cấp dành cho nam",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Da Nam",
                            price = 280000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6404)
                        },
                        new
                        {
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "80%",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6409),
                            description = "Áo thun cotton mềm mại dành cho trang phục thường ngày",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Cotton Nữ",
                            price = 340000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6410)
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.Property<Guid>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("productImageId");

                    b.HasIndex("productId");

                    b.ToTable("tblProductImages");

                    b.HasData(
                        new
                        {
                            productImageId = new Guid("9521c2a6-ff21-4359-95fe-9f63f7a83ddb"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("d73c4941-736f-4968-9e2d-cfaaff9947a1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("5458733a-5fef-4de9-861e-c41ae08aba2b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("b69df2e5-bbed-4a0f-b9e5-46f28aa05a37"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("44d5da70-7bba-4c0e-8e2c-b9cfed1e891b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("4945632a-31d7-43f1-bb5c-4a6ba94f58cd"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("0ad75479-bba5-4934-9575-3eb871bc229d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("db8284a6-63b9-42c0-8591-c513a610e16a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("b0ea08c0-759a-4f76-9b69-58a1d5b93c1b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("1532c77f-d4b9-4fdd-89fa-71cf67d4a7f0"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("c126611a-1723-4061-9e54-44fb894ebce1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("00b96d4c-7b50-4f0a-bab8-4c6d295e76e4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("e29895a0-df07-4565-bfd4-84fcb8ff7ecf"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("0d00d209-ddd4-49db-ab50-fe1fefeeadde"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("bdceef44-5b85-4df4-9b16-882ea45c9196"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("b0d1f42f-68e6-4d42-a717-adca773d2fe1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("a6bb13a1-40bb-4c95-9712-7ae8c6ba072d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("95b84622-089a-4f5a-b7bc-989c45f72364"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("934775b5-e5da-4c8f-8982-0dae1e70a1a7"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("92708b31-be1f-42b3-a5e2-920e01221267"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("6fd284b6-8b1d-4de7-b874-ba629ee9597a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("4b04d3d6-6285-42e9-bf0c-5be79c4cc9a1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("17ca1155-93c7-4ed2-b3c4-9e98abc4c6c7"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("a67ca932-24c4-49c0-a823-79860e2019bd"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("2bb08be1-ff25-4b0f-af31-e4247bbe9031"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("8cc57209-255c-443d-90af-d30bdcce04a9"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("7477b309-a4d0-4b1f-be66-9f25522fc990"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("b7619253-68db-4d4d-85c1-e669091c7045"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("ba5fec1d-1081-4324-8187-aae3b80b9e36"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("1164bbe7-6c44-4c3a-9624-80108fca1861"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("cc43d027-807c-4d17-8eea-009af6b73259"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("12547ef4-698c-435e-83b9-2c38b9d9217e"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("d431c376-77ce-4dab-a279-5dff86eff58a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("f98e61c5-e306-47e8-8bd2-4ac61c1d93d3"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("601458f5-dbb6-46f6-8aa2-02e9505c1f30"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("4a69d0c0-33ae-4c9e-aad9-2a6ceb534292"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("f5bde0ac-ea9b-4061-b03a-ecb73a1dcf3e"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("499ceb12-abd6-4588-b304-70817894cbea"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("3a458124-ecd7-407d-ae5f-f08fb9900287"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("0e5a6cc9-b761-4fa5-9657-dfb84aa12ff5"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.Property<Guid>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TblProductproductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("shopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("reviewId");

                    b.HasIndex("TblProductproductId");

                    b.HasIndex("shopId");

                    b.HasIndex("userId");

                    b.ToTable("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Property<Guid?>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("tblRoles");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "User"
                        },
                        new
                        {
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Property<Guid?>("sizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sizeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sizeId");

                    b.ToTable("tblSizes");

                    b.HasData(
                        new
                        {
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            sizeName = "S"
                        },
                        new
                        {
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            sizeName = "M"
                        },
                        new
                        {
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            sizeName = "L"
                        },
                        new
                        {
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            sizeName = "XL"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Property<Guid?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isShopOwner")
                        .HasColumnType("bit");

                    b.Property<string>("passWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("shopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            userId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(5956),
                            email = "user1@gmail.com",
                            isShopOwner = true,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0909123456",
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            shopAddress = "shop1address",
                            shopDescription = "shop1des",
                            shopLogo = "shop1logo",
                            shopName = "shop1",
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(5973),
                            userName = "user1"
                        },
                        new
                        {
                            userId = new Guid("e2c3c2b1-5a1f-4c4f-b1ea-6b2c4f8e1a0b"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6003),
                            email = "admin@gmail.com",
                            isShopOwner = false,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0912398765",
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            updatedAt = new DateTime(2024, 10, 6, 22, 26, 38, 925, DateTimeKind.Local).AddTicks(6003),
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblCarts")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("cartId");

                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("productId");

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblFavorites")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblFavorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblOrderHistories")
                        .HasForeignKey("cartId");

                    b.Navigation("cart");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCategory", "category")
                        .WithMany("tblProducts")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EXE201_2RE_API.Models.TblGenderCategory", "genderCategory")
                        .WithMany("tblProducts")
                        .HasForeignKey("genderCategoryId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shopOwner")
                        .WithMany("tblProducts")
                        .HasForeignKey("shopOwnerId");

                    b.HasOne("EXE201_2RE_API.Models.TblSize", "size")
                        .WithMany("tblProducts")
                        .HasForeignKey("sizeId");

                    b.Navigation("category");

                    b.Navigation("genderCategory");

                    b.Navigation("shopOwner");

                    b.Navigation("size");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblProductImages")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", null)
                        .WithMany("tblReviews")
                        .HasForeignKey("TblProductproductId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shop")
                        .WithMany("reviewsReceivedAsShop")
                        .HasForeignKey("shopId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("reviewsWritten")
                        .HasForeignKey("userId");

                    b.Navigation("shop");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblRole", "role")
                        .WithMany("tblUsers")
                        .HasForeignKey("roleId");

                    b.Navigation("role");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProductImages");

                    b.Navigation("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Navigation("reviewsReceivedAsShop");

                    b.Navigation("reviewsWritten");

                    b.Navigation("tblCarts");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
