// <auto-generated />
using System;
using EXE201_2RE_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201_2RE_API.Migrations
{
    [DbContext(typeof(EXE201Context))]
    [Migration("20241006152544_updateEntitiesV2")]
    partial class updateEntitiesV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Property<Guid?>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartId");

                    b.HasIndex("userId");

                    b.ToTable("tblCarts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.Property<Guid?>("cartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartDetailId");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("tblCartDetails");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Property<Guid?>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("tblCategories");

                    b.HasData(
                        new
                        {
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            name = "Áo Thun"
                        },
                        new
                        {
                            categoryId = new Guid("a7b8c9d8-3e2a-4b9b-b9f7-5e6a7c8e9f0b"),
                            name = "Quần Jeans"
                        },
                        new
                        {
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            name = "Áo Khoác"
                        },
                        new
                        {
                            categoryId = new Guid("e2b3d5a6-3e4f-5a6b-c8d9-2f2b3e5a7b8c"),
                            name = "Váy"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.Property<Guid?>("favoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("productId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("favoriteId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblFavorites");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Property<Guid?>("genderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderCategoryId");

                    b.ToTable("tblGenderCategories");

                    b.HasData(
                        new
                        {
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Nam"
                        },
                        new
                        {
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Nữ"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.Property<Guid?>("orderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("changedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderHistoryId");

                    b.HasIndex("cartId");

                    b.ToTable("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("categoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("genderCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("shopOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("genderCategoryId");

                    b.HasIndex("shopOwnerId");

                    b.HasIndex("sizeId");

                    b.ToTable("tblProducts");

                    b.HasData(
                        new
                        {
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5589),
                            description = "Áo thun cổ điển dành cho nam, có nhiều kích cỡ",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Cổ Điển Nam",
                            price = 200000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5591)
                        },
                        new
                        {
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5599),
                            description = "Quần jeans slim fit với kiểu dáng hiện đại",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Slim Fit Nam",
                            price = 300000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5599)
                        },
                        new
                        {
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "96%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5606),
                            description = "Áo khoác thường cho ngày thường",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Thường Nam",
                            price = 400000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5607)
                        },
                        new
                        {
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5614),
                            description = "Áo thun ôm thoải mái cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Ôm Nữ",
                            price = 250000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5617)
                        },
                        new
                        {
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "89%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5622),
                            description = "Quần jeans ôm thời trang cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Quần Jeans Ôm Nữ",
                            price = 350000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5623)
                        },
                        new
                        {
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5629),
                            description = "Áo khoác thời trang và ấm áp cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Khoác Thường Nữ",
                            price = 500000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5636),
                            description = "Áo thun họa tiết thời trang với thiết kế đẹp",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Họa Tiết Nam",
                            price = 290000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5637)
                        },
                        new
                        {
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "85%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5643),
                            description = "Quần jeans regular fit cổ điển",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Regular Fit Nam",
                            price = 440000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5644)
                        },
                        new
                        {
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b"),
                            brand = "Nike",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "70%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5650),
                            description = "Áo khoác da cao cấp dành cho nam",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Da Nam",
                            price = 280000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "80%",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5657),
                            description = "Áo thun cotton mềm mại dành cho trang phục thường ngày",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Cotton Nữ",
                            price = 340000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5657)
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.Property<Guid>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("productImageId");

                    b.HasIndex("productId");

                    b.ToTable("tblProductImages");

                    b.HasData(
                        new
                        {
                            productImageId = new Guid("8f274025-ffaf-4667-90f5-c5250523f772"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("172e3484-d594-47b2-a6b5-9bacdbe5a70b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("ddd36da9-146c-4876-a676-a9b6ce174748"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("822f8305-3be2-45b0-8f81-9121658d95ed"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("a26c6914-5d3f-4761-9cb9-1b8ab381226a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("39409e3b-cad5-4637-8fa4-b803e4d97805"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("d1aa50d3-b5cf-40c7-9c5b-c5df83ba0cce"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("91cf6aff-5090-4c17-8131-0d4bac6d594c"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("72f0dce9-df34-4216-bad0-8902907e288f"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("3ccd1af2-3eec-450c-9f18-16adebb90381"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("a046859e-898f-4d47-bce4-ff416a6cea07"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("57d5bfca-4985-44ec-a17d-2d3ef5bdfee2"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("7635cf2e-00c9-4d07-b398-eb648239e4da"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("1ac3e9be-00dc-4dcb-bd1d-0c9aa2d35c14"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("f4cfcb8b-3f5d-4ab2-92dc-ed68c411a7bf"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("dca21527-2617-4c68-91cf-a43d6e66da44"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("fd7912a3-c226-4521-837c-0a27fed2d478"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("6d518a2d-99b1-4dfe-81b7-ad5be6ae1292"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("230ae376-2322-4ba0-a317-1ca305996394"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("f05b5e36-e8e8-4e6b-8738-7c2a2db58113"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("f3480f3a-d004-4864-9b1e-efc62d094bc4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("d6be0f46-541a-42c5-bac2-4727e9ce4592"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("9a6174a5-ecd9-42ac-94f0-ff767c2784c0"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("84dd29bf-f911-463b-8a8c-fe975bdfae28"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("754989be-31a7-4462-9fb3-5b4d7c1112e4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("98d76f72-27ce-4cf3-908f-1b9f03a08570"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("c1445ba1-eafc-41fe-a5d6-65430cff00fe"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("0a087b01-f760-4576-8aa4-cc24d299d9ed"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("2e4baeee-de29-4de1-bc05-4a638c63d638"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("f9f19df6-b999-4e66-916d-a9ae77f4fade"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("205c028c-b77c-47c7-adbc-845c6298c44a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("ab9ce07f-a993-4f19-a730-1e7e21a84f29"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("49e207fc-3adb-4661-9109-028fd758a043"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("d7846b1f-384b-4269-b814-fb0363d81d53"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("1faa5606-3859-477d-ad74-44dcdf330ac2"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("34e764d1-9688-4598-80c7-5f76c8bc377b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("319d251a-7682-47e2-a052-53c1d4fcc07e"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("27fc80aa-6216-45a1-b95f-c78ec994f31d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("c0ad8dae-d5a7-43b2-b2ec-5e141b706bc3"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("32d76376-b575-4f56-bda5-3e9cc74841dd"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.Property<Guid>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TblProductproductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("shopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("reviewId");

                    b.HasIndex("TblProductproductId");

                    b.HasIndex("shopId");

                    b.HasIndex("userId");

                    b.ToTable("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Property<Guid?>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("tblRoles");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "User"
                        },
                        new
                        {
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Property<Guid?>("sizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sizeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sizeId");

                    b.ToTable("tblSizes");

                    b.HasData(
                        new
                        {
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            sizeName = "S"
                        },
                        new
                        {
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            sizeName = "M"
                        },
                        new
                        {
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            sizeName = "L"
                        },
                        new
                        {
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            sizeName = "XL"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Property<Guid?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isShopOwner")
                        .HasColumnType("bit");

                    b.Property<string>("passWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("shopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            userId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5188),
                            email = "user1@gmail.com",
                            isShopOwner = true,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0909123456",
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            shopAddress = "shop1address",
                            shopDescription = "shop1des",
                            shopLogo = "shop1logo",
                            shopName = "shop1",
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5203),
                            userName = "user1"
                        },
                        new
                        {
                            userId = new Guid("e2c3c2b1-5a1f-4c4f-b1ea-6b2c4f8e1a0b"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5243),
                            email = "admin@gmail.com",
                            isShopOwner = false,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0912398765",
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            updatedAt = new DateTime(2024, 10, 6, 22, 25, 43, 884, DateTimeKind.Local).AddTicks(5244),
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblCarts")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("cartId");

                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("productId");

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblFavorites")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblFavorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblOrderHistories")
                        .HasForeignKey("cartId");

                    b.Navigation("cart");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCategory", "category")
                        .WithMany("tblProducts")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EXE201_2RE_API.Models.TblGenderCategory", "genderCategory")
                        .WithMany("tblProducts")
                        .HasForeignKey("genderCategoryId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shopOwner")
                        .WithMany("tblProducts")
                        .HasForeignKey("shopOwnerId");

                    b.HasOne("EXE201_2RE_API.Models.TblSize", "size")
                        .WithMany("tblProducts")
                        .HasForeignKey("sizeId");

                    b.Navigation("category");

                    b.Navigation("genderCategory");

                    b.Navigation("shopOwner");

                    b.Navigation("size");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblProductImages")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", null)
                        .WithMany("tblReviews")
                        .HasForeignKey("TblProductproductId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shop")
                        .WithMany("reviewsReceivedAsShop")
                        .HasForeignKey("shopId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("reviewsWritten")
                        .HasForeignKey("userId");

                    b.Navigation("shop");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblRole", "role")
                        .WithMany("tblUsers")
                        .HasForeignKey("roleId");

                    b.Navigation("role");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProductImages");

                    b.Navigation("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Navigation("reviewsReceivedAsShop");

                    b.Navigation("reviewsWritten");

                    b.Navigation("tblCarts");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
