// <auto-generated />
using System;
using EXE201_2RE_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201_2RE_API.Migrations
{
    [DbContext(typeof(EXE201Context))]
    [Migration("20241006142621_updateDb")]
    partial class updateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Property<Guid?>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartId");

                    b.HasIndex("userId");

                    b.ToTable("tblCarts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.Property<Guid?>("cartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartDetailId");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("tblCartDetails");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Property<Guid?>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("tblCategories");

                    b.HasData(
                        new
                        {
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            name = "Áo Thun"
                        },
                        new
                        {
                            categoryId = new Guid("a7b8c9d8-3e2a-4b9b-b9f7-5e6a7c8e9f0b"),
                            name = "Quần Jeans"
                        },
                        new
                        {
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            name = "Áo Khoác"
                        },
                        new
                        {
                            categoryId = new Guid("e2b3d5a6-3e4f-5a6b-c8d9-2f2b3e5a7b8c"),
                            name = "Váy"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.Property<Guid?>("favoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("productId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("favoriteId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblFavorites");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Property<Guid?>("genderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderCategoryId");

                    b.ToTable("tblGenderCategories");

                    b.HasData(
                        new
                        {
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Nam"
                        },
                        new
                        {
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Nữ"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.Property<Guid?>("orderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("changedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderHistoryId");

                    b.HasIndex("cartId");

                    b.ToTable("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("categoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("genderCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("shopOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("genderCategoryId");

                    b.HasIndex("shopOwnerId");

                    b.HasIndex("sizeId");

                    b.ToTable("tblProducts");

                    b.HasData(
                        new
                        {
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e"),
                            brand = "Nike",
                            categoryId = new Guid("f1aee1c7-6d5e-4e87-a5ea-3a5d6e7c8f9a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7615),
                            description = "Áo thun cổ điển dành cho nam, có nhiều kích cỡ",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Cổ Điển Nam",
                            price = 200000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7617)
                        },
                        new
                        {
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d"),
                            brand = "Nike",
                            categoryId = new Guid("d9b4c8c3-3a2e-4b9b-b9f7-5e6a7c8e9f0b"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7626),
                            description = "Quần jeans slim fit với kiểu dáng hiện đại",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Slim Fit Nam",
                            price = 300000m,
                            shopOwnerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7626)
                        },
                        new
                        {
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7"),
                            brand = "Adidas",
                            categoryId = new Guid("a5e1d2b3-2f3c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "96%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7632),
                            description = "Áo khoác thường cho ngày thường",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Thường Nam",
                            price = 400000m,
                            shopOwnerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7632)
                        },
                        new
                        {
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f"),
                            brand = "Adidas",
                            categoryId = new Guid("f1aee1c7-6d5e-4e87-a5ea-3a5d6e7c8f9a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7637),
                            description = "Áo thun ôm thoải mái cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Ôm Nữ",
                            price = 250000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7638)
                        },
                        new
                        {
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a"),
                            brand = "Puma",
                            categoryId = new Guid("d9b4c8c3-3a2e-4b9b-b9f7-5e6a7c8e9f0b"),
                            condition = "89%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7644),
                            description = "Quần jeans ôm thời trang cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Quần Jeans Ôm Nữ",
                            price = 350000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7644)
                        },
                        new
                        {
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10"),
                            brand = "Adidas",
                            categoryId = new Guid("a5e1d2b3-2f3c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7651),
                            description = "Áo khoác thời trang và ấm áp cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Khoác Thường Nữ",
                            price = 500000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7652)
                        },
                        new
                        {
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f"),
                            brand = "Nike",
                            categoryId = new Guid("f1aee1c7-6d5e-4e87-a5ea-3a5d6e7c8f9a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7658),
                            description = "Áo thun họa tiết thời trang với thiết kế đẹp",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Họa Tiết Nam",
                            price = 290000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7659)
                        },
                        new
                        {
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a"),
                            brand = "Puma",
                            categoryId = new Guid("d9b4c8c3-3a2e-4b9b-b9f7-5e6a7c8e9f0b"),
                            condition = "85%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7665),
                            description = "Quần jeans regular fit cổ điển",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Regular Fit Nam",
                            price = 440000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7665)
                        },
                        new
                        {
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b"),
                            brand = "Nike",
                            categoryId = new Guid("a5e1d2b3-2f3c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "70%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7670),
                            description = "Áo khoác da cao cấp dành cho nam",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Da Nam",
                            price = 280000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7671)
                        },
                        new
                        {
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e"),
                            brand = "Adidas",
                            categoryId = new Guid("f1aee1c7-6d5e-4e87-a5ea-3a5d6e7c8f9a"),
                            condition = "80%",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7676),
                            description = "Áo thun cotton mềm mại dành cho trang phục thường ngày",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Cotton Nữ",
                            price = 340000m,
                            shopOwnerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7677)
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.Property<Guid>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("productImageId");

                    b.HasIndex("productId");

                    b.ToTable("tblProductImages");

                    b.HasData(
                        new
                        {
                            productImageId = new Guid("a65aa6e6-e344-4be5-afbc-8cf5dd7e0503"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("418f39b3-e3ba-4d65-b9a6-1edf6acd64c4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("dce55007-ab78-461c-a692-b2ddd7ae389a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("c4b23605-765d-4c6d-b74d-8006157b5524"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("c022a63a-0831-4395-9d81-d6efcb193713"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("64c6d15d-d9d6-4864-af10-047356981462"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("047aa3a9-1479-47e9-8f77-6ccf35f07a0c"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("0481c515-5fb4-46d5-89d1-f2a07e9075dd"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("c51f1244-32d0-4cc2-8b10-e7702a9acb06"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("dd75582e-b01e-4a36-9829-559d83a28521"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("c2eee380-90a5-4c97-8044-d4c0bcb0c835"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("9fa4c63d-6a45-45c3-9d85-ac8c6cd24687"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("125c0e2c-7d06-4d88-a681-d9b4edb3e222"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("f10a5e03-e30f-4f94-b973-77e2f3cb7446"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("ad3baeb0-b6bd-4d71-8409-4846dbab8413"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("504b2f21-4ad0-40a2-bace-3920231762cb"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("0b02f17f-65d5-4894-9f34-860f1c0327fc"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("41754043-05e7-4673-9f30-a6a4870b920e"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("5c8f0147-e288-4dc0-9df3-5af5ec64eb5d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("5371f5db-d27e-4d34-a156-b24455a89386"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("da49f2c8-fff9-434d-9108-64db01b702e4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("b922c4a7-1aca-4ed7-86f1-f6fd73926828"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("290befb5-2c30-4159-9e75-4f18cd2a7da9"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("b5f6552e-bdff-41bc-a6e0-2f60f39d4f5d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("7571fbf6-6afb-49c0-8f9a-90a19950d5d3"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("c374a3ec-bfdd-42cc-a658-d0f116a95a12"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("82e9aa95-065a-4368-8de4-3a8623c4ea46"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("6eae6770-7f72-46da-86f2-97141da26211"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("2861560c-d9c2-4e95-991d-8a0ad062f24f"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("a0ae380a-8985-43c0-812e-dcbc08daa500"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("174f3e29-82c3-49e7-b0f6-a8179dc0d256"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("268ddac1-f2bd-4a7e-b568-62995b24977f"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("cc514a41-832a-49a5-8df0-e49d72e72e2b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("33478450-5088-4980-aedc-e433ce33bb91"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("cc7da5e1-f97c-4eac-a401-11ad18c13c33"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("068534a9-ea90-4227-b969-0e3cdf612736"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("8a7a32df-c720-44e5-87fc-9cdae8933d1d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("f4be140f-d11b-484f-81a8-feaeba6471c1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("10e5cfd8-1d15-4e08-8bdd-afd8fc49a622"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("d1613990-b95b-4d0c-8b95-883b929e3801"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.Property<Guid>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("reviewId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Property<Guid?>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("tblRoles");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "User"
                        },
                        new
                        {
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Property<Guid?>("sizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sizeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sizeId");

                    b.ToTable("tblSizes");

                    b.HasData(
                        new
                        {
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            sizeName = "S"
                        },
                        new
                        {
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            sizeName = "M"
                        },
                        new
                        {
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            sizeName = "L"
                        },
                        new
                        {
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            sizeName = "XL"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Property<Guid?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isShopOwner")
                        .HasColumnType("bit");

                    b.Property<string>("passWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("shopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            userId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7236),
                            email = "user1@gmail.com",
                            isShopOwner = true,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0909123456",
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            shopAddress = "shop1address",
                            shopDescription = "shop1des",
                            shopLogo = "shop1logo",
                            shopName = "shop1",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7248),
                            userName = "user1"
                        },
                        new
                        {
                            userId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7320),
                            email = "shop2@gmail.com",
                            isShopOwner = true,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0909123123",
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            shopAddress = "shop2address",
                            shopDescription = "shop2des",
                            shopLogo = "shop2logo",
                            shopName = "shop2",
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7321),
                            userName = "shop2"
                        },
                        new
                        {
                            userId = new Guid("e2c3c2b1-5a1f-4c4f-b1ea-6b2c4f8e1a0b"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7350),
                            email = "admin@gmail.com",
                            isShopOwner = false,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0912398765",
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            updatedAt = new DateTime(2024, 10, 6, 21, 26, 21, 14, DateTimeKind.Local).AddTicks(7351),
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblCarts")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("cartId");

                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("productId");

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblFavorites")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblFavorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblOrderHistories")
                        .HasForeignKey("cartId");

                    b.Navigation("cart");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCategory", "category")
                        .WithMany("tblProducts")
                        .HasForeignKey("categoryId");

                    b.HasOne("EXE201_2RE_API.Models.TblGenderCategory", "genderCategory")
                        .WithMany("tblProducts")
                        .HasForeignKey("genderCategoryId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shopOwner")
                        .WithMany("tblProducts")
                        .HasForeignKey("shopOwnerId");

                    b.HasOne("EXE201_2RE_API.Models.TblSize", "size")
                        .WithMany("tblProducts")
                        .HasForeignKey("sizeId");

                    b.Navigation("category");

                    b.Navigation("genderCategory");

                    b.Navigation("shopOwner");

                    b.Navigation("size");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblProductImages")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblReviews")
                        .HasForeignKey("productId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblReviews")
                        .HasForeignKey("userId");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblRole", "role")
                        .WithMany("tblUsers")
                        .HasForeignKey("roleId");

                    b.Navigation("role");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProductImages");

                    b.Navigation("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Navigation("tblCarts");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProducts");

                    b.Navigation("tblReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
