// <auto-generated />
using System;
using EXE201_2RE_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201_2RE_API.Migrations
{
    [DbContext(typeof(EXE201Context))]
    partial class EXE201ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Property<Guid?>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartId");

                    b.HasIndex("userId");

                    b.ToTable("tblCarts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.Property<Guid?>("cartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cartDetailId");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("tblCartDetails");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Property<Guid?>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("tblCategories");

                    b.HasData(
                        new
                        {
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            name = "Áo Thun"
                        },
                        new
                        {
                            categoryId = new Guid("a7b8c9d8-3e2a-4b9b-b9f7-5e6a7c8e9f0b"),
                            name = "Quần Jeans"
                        },
                        new
                        {
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            name = "Áo Khoác"
                        },
                        new
                        {
                            categoryId = new Guid("e2b3d5a6-3e4f-5a6b-c8d9-2f2b3e5a7b8c"),
                            name = "Váy"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.Property<Guid?>("favoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("productId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("userId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("favoriteId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblFavorites");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Property<Guid?>("genderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderCategoryId");

                    b.ToTable("tblGenderCategories");

                    b.HasData(
                        new
                        {
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Nam"
                        },
                        new
                        {
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Nữ"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.Property<Guid?>("orderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("changedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderHistoryId");

                    b.HasIndex("cartId");

                    b.ToTable("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("categoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("genderCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("shopOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("sizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("genderCategoryId");

                    b.HasIndex("shopOwnerId");

                    b.HasIndex("sizeId");

                    b.ToTable("tblProducts");

                    b.HasData(
                        new
                        {
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1225),
                            description = "Áo thun cổ điển dành cho nam, có nhiều kích cỡ",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Cổ Điển Nam",
                            price = 200000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1226)
                        },
                        new
                        {
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1232),
                            description = "Quần jeans slim fit với kiểu dáng hiện đại",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Slim Fit Nam",
                            price = 300000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1233)
                        },
                        new
                        {
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "96%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1238),
                            description = "Áo khoác thường cho ngày thường",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Thường Nam",
                            price = 400000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1239)
                        },
                        new
                        {
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "90%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1244),
                            description = "Áo thun ôm thoải mái cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Ôm Nữ",
                            price = 250000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1245)
                        },
                        new
                        {
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "89%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1250),
                            description = "Quần jeans ôm thời trang cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Quần Jeans Ôm Nữ",
                            price = 350000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1250)
                        },
                        new
                        {
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10"),
                            brand = "Adidas",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1255),
                            description = "Áo khoác thời trang và ấm áp cho nữ",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Khoác Thường Nữ",
                            price = 500000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1256)
                        },
                        new
                        {
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f"),
                            brand = "Nike",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "99%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1262),
                            description = "Áo thun họa tiết thời trang với thiết kế đẹp",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Thun Họa Tiết Nam",
                            price = 290000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1262)
                        },
                        new
                        {
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a"),
                            brand = "Puma",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "85%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1295),
                            description = "Quần jeans regular fit cổ điển",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Quần Jeans Regular Fit Nam",
                            price = 440000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1296)
                        },
                        new
                        {
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b"),
                            brand = "Nike",
                            categoryId = new Guid("c5e1f2b8-2f4c-4b3d-b7a8-4c5e6f7d8b9a"),
                            condition = "70%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1301),
                            description = "Áo khoác da cao cấp dành cho nam",
                            genderCategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "Áo Khoác Da Nam",
                            price = 280000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1302)
                        },
                        new
                        {
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e"),
                            brand = "Adidas",
                            categoryId = new Guid("f8a8e1c5-4b3c-4e8f-b8ea-3f3f6e9c2f1a"),
                            condition = "80%",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1308),
                            description = "Áo thun cotton mềm mại dành cho trang phục thường ngày",
                            genderCategoryId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Áo Thun Cotton Nữ",
                            price = 340000m,
                            shopOwnerId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            status = "Có sẵn",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(1308)
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.Property<Guid>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("productImageId");

                    b.HasIndex("productId");

                    b.ToTable("tblProductImages");

                    b.HasData(
                        new
                        {
                            productImageId = new Guid("fedb06d0-04e2-4128-aa7a-ad53bbe62e21"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("a7566b21-f160-4456-8a05-77002da4f7a9"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("0f9435b2-627c-47d7-9ed7-024df4bd0e73"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("d4711190-456a-42b1-ae6d-d88b2d9187e4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("5a6e2f3e-9c3e-4f87-9e8c-ea1d4f6e8b0e")
                        },
                        new
                        {
                            productImageId = new Guid("e3ebb4e8-bb1d-4da1-874a-34594c749288"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("13034738-4373-4cc7-b3a4-3955a097a1f4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("40a7182c-8bbb-45cb-b967-18220990f3bd"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("23394f2b-af2b-4bbf-8ab6-f82b56a2c8ec"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("c28c2e4e-2e0a-4a4f-b3e7-8c9a9b8d5c5d")
                        },
                        new
                        {
                            productImageId = new Guid("df86adf4-9c90-4690-8a66-9d3b0f71ea79"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("47547702-d01b-4eb7-9c3c-4c04934bca2f"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("738de10f-b987-40d6-883d-1562388c890e"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("9f60d560-ae52-4a88-8623-fa9ede2bf4f7"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b12cc9b8-4a9d-44e9-bf40-8b3e8e5cc8c7")
                        },
                        new
                        {
                            productImageId = new Guid("6a9e9c65-fd3b-46cd-ada7-10317ff986d8"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("c0b19fe7-5a29-4699-832c-cfe369314cb5"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("8050d085-80c5-4a8f-9ac8-294871297d3b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("68b75258-4aea-497a-857b-d972b783c1fc"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("f2b7f7a4-6a34-43b0-bc18-4e8e3e8a7c8f")
                        },
                        new
                        {
                            productImageId = new Guid("040d4bc4-bf62-46cd-bf11-db40fe29666b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("e20430b2-cfd9-4cb6-8ff6-1b70f8f291ce"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("43e56a62-3be8-4126-8d80-fb77acef635c"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("fe024b71-563b-447d-a573-3c9ef43aaef4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("0b6c1c6c-2f3f-4d3a-9e1b-1d5e3e9b2c3a")
                        },
                        new
                        {
                            productImageId = new Guid("35d2bb64-a141-4572-8e5f-805723859a5a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("a2b770b9-283a-47f7-89c2-03821b1d5c80"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("b63695ed-15d3-4664-847f-f259a5ff54e4"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("2bf3cd11-2527-4b1a-94eb-71f79788a961"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("d1e7a8d2-1c34-4e91-bc1f-1a4e5f9a8e10")
                        },
                        new
                        {
                            productImageId = new Guid("d5bdfae8-8697-4063-83bb-377dd9fec551"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("18a5b7e5-0a9e-4813-a822-78a106b880ea"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("d74ef2a8-16b7-4bd3-b09f-a01844489b95"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("b5301688-7a41-4e42-a54c-5ef7a2acf832"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("e6b8f3b5-a4c5-4a2d-8e38-6d4c1e2a9a8f")
                        },
                        new
                        {
                            productImageId = new Guid("ed5caff0-b521-4bd0-bc40-6c93d673790c"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("b4fb287c-2c78-4a7e-995c-8ba2492560f9"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("d773674c-6e85-4f05-bddd-c5a0260c5866"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("329f44c4-05d0-4cfd-a29e-9df939aaaee1"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("a7c2d1f4-2b6e-4e18-bf7f-8d5e3f1b9c4a")
                        },
                        new
                        {
                            productImageId = new Guid("be9d94dd-c198-4566-b734-8970d3d37947"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("78ad4454-bf28-489d-80bc-e933248cd24b"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("65c5a04c-9c54-45ff-9f44-8b7a48d1df1a"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("b6d33659-a328-4385-a34b-4ec8f2d98b5d"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("b1f8c9e3-3e2b-4c4d-8e1a-2e6f5c3d8e0b")
                        },
                        new
                        {
                            productImageId = new Guid("ba49b96d-4fb1-460e-91a3-fd0247d977b0"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("78e1d543-81a1-4f4f-a624-a1bd29365620"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("6748689c-b9a6-40f7-9609-bad5c4ecef90"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        },
                        new
                        {
                            productImageId = new Guid("3c0bf920-16d5-4391-9463-460c067e66af"),
                            imageUrl = "https://down-vn.img.susercontent.com/file/c7db377b177fc8e2ff75a769022dcc23",
                            productId = new Guid("9c2b3e7d-4a8a-4b1c-9e3f-2f6e8a5d9b4e")
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.Property<Guid>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("reviewId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Property<Guid?>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("tblRoles");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            name = "User"
                        },
                        new
                        {
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Property<Guid?>("sizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sizeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sizeId");

                    b.ToTable("tblSizes");

                    b.HasData(
                        new
                        {
                            sizeId = new Guid("d4f1c0e1-2d41-4f0e-bc9f-4b85b6c5f4a2"),
                            sizeName = "S"
                        },
                        new
                        {
                            sizeId = new Guid("e5a1b4d6-5c4c-4f0e-bc9f-4b85b6c5f4a3"),
                            sizeName = "M"
                        },
                        new
                        {
                            sizeId = new Guid("f6b2e8a7-7d5f-4f0e-bc9f-4b85b6c5f4a4"),
                            sizeName = "L"
                        },
                        new
                        {
                            sizeId = new Guid("a7c3f9b8-8e6f-4f0e-bc9f-4b85b6c5f4a5"),
                            sizeName = "XL"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Property<Guid?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isShopOwner")
                        .HasColumnType("bit");

                    b.Property<string>("passWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("shopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            userId = new Guid("b1a3e477-9f5e-4bff-ae0a-5e8b42e0f8a0"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(898),
                            email = "user1@gmail.com",
                            isShopOwner = true,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0909123456",
                            roleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            shopAddress = "shop1address",
                            shopDescription = "shop1des",
                            shopLogo = "shop1logo",
                            shopName = "shop1",
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(917),
                            userName = "user1"
                        },
                        new
                        {
                            userId = new Guid("e2c3c2b1-5a1f-4c4f-b1ea-6b2c4f8e1a0b"),
                            address = "address",
                            createdAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(954),
                            email = "admin@gmail.com",
                            isShopOwner = false,
                            passWord = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            phoneNumber = "0912398765",
                            roleId = new Guid("c9ebf5d5-d6b4-4c1d-bc12-fc4b8f1f4c61"),
                            updatedAt = new DateTime(2024, 10, 6, 21, 41, 43, 660, DateTimeKind.Local).AddTicks(955),
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblCarts")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCartDetail", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("cartId");

                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblCartDetails")
                        .HasForeignKey("productId");

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblFavorite", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblFavorites")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblFavorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblOrderHistory", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCart", "cart")
                        .WithMany("tblOrderHistories")
                        .HasForeignKey("cartId");

                    b.Navigation("cart");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblCategory", "category")
                        .WithMany("tblProducts")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EXE201_2RE_API.Models.TblGenderCategory", "genderCategory")
                        .WithMany("tblProducts")
                        .HasForeignKey("genderCategoryId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "shopOwner")
                        .WithMany("tblProducts")
                        .HasForeignKey("shopOwnerId");

                    b.HasOne("EXE201_2RE_API.Models.TblSize", "size")
                        .WithMany("tblProducts")
                        .HasForeignKey("sizeId");

                    b.Navigation("category");

                    b.Navigation("genderCategory");

                    b.Navigation("shopOwner");

                    b.Navigation("size");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProductImage", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblProductImages")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblReview", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblProduct", "product")
                        .WithMany("tblReviews")
                        .HasForeignKey("productId");

                    b.HasOne("EXE201_2RE_API.Models.TblUser", "user")
                        .WithMany("tblReviews")
                        .HasForeignKey("userId");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.HasOne("EXE201_2RE_API.Models.TblRole", "role")
                        .WithMany("tblUsers")
                        .HasForeignKey("roleId");

                    b.Navigation("role");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCart", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblOrderHistories");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblGenderCategory", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblProduct", b =>
                {
                    b.Navigation("tblCartDetails");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProductImages");

                    b.Navigation("tblReviews");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblRole", b =>
                {
                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblSize", b =>
                {
                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("EXE201_2RE_API.Models.TblUser", b =>
                {
                    b.Navigation("tblCarts");

                    b.Navigation("tblFavorites");

                    b.Navigation("tblProducts");

                    b.Navigation("tblReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
