// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblOrderHistory
{
    [Key]
    public int OrderHistoryId { get; set; }

    public int? CartId { get; set; }

    public string Status { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual TblCart Cart { get; set; }
}